### ISSUE TITLE
error retrieving potential energy for calculations without scf=xqc

### ISSUE THREAD

**Issue by lmoranglez** [maserasgroup-repo/pyssian-utils#5]
When pyssian-thermo.py script reads an output with a total **-1 charge**, an error message (as depicted below) pops up:
I guess it might be due to the minus symbol?

Traceback (most recent call last):
  File "/home/lmoran/Documents/VirtualEnvironment/python3/bin/pyssian-thermo.py", line 75, in <module>
    raise e
  File "/home/lmoran/Documents/VirtualEnvironment/python3/bin/pyssian-thermo.py", line 72, in <module>
    U = potential_energy(GOF,args.Method)
  File "/home/lmoran/Documents/VirtualEnvironment/python3/lib/python3.7/site-packages/pyssianutils/functions.py", line 74, in potential_energy
    energy = GOF.get_links(508)[-1].energy
IndexError: list index out of range

I can send you an example file. 

Thank you, 
Lucía

**Comment by rperezsoto** [comment]
It seems an error in the potential_energy function from the functions module. Should be fixed now in the develop branch.
